### PR TITLE
add index.js hi

### PR DESCRIPTION
**Pull request by Rajarshi-Manna**
Test description

#  1
# 2

### CODE REVIEW

**Comment by rajarshi433** [comment]
well done

**Comment by rajarshi433** [comment]
hi

**Comment by rajarshi433** [comment]
hello

**Comment by Rajarshi-Manna** [comment]
hmmmmm

**Comment by rajarshi433** [comment]
aaaaaaaaa

**Comment by Rajarshi-Manna** [comment]
bbbbbbbbb

**Pull request merged**
